"""Initial migration

Revision ID: c97d9c8ce793
Revises: 
Create Date: 2025-08-30 15:01:55.245517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97d9c8ce793'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('ubicacion')
    )
    op.create_index(op.f('ix_deposito_id'), 'deposito', ['id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('deposito_origen_id', sa.Integer(), nullable=False),
    sa.Column('deposito_destino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deposito_destino_id'], ['deposito.id'], ),
    sa.ForeignKeyConstraint(['deposito_origen_id'], ['deposito.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimiento_id'), 'movimiento', ['id'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_movimiento_id'), table_name='movimiento')
    op.drop_table('movimiento')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_deposito_id'), table_name='deposito')
    op.drop_table('deposito')
    # ### end Alembic commands ###
